### ISSUE TITLE
Move off aurora

### ISSUE THREAD

**Issue by wagnerand** [mozilla/python-spidermonkey#10]
Aurora is no longer, so we should either move to beta or nightly.

Thoughts @EnTeQuAk ?

**Comment by EnTeQuAk** [comment]
If I understood the aurora mails correctly nightly should be the favorable build but given that we don't want to have nightly releases of python-spidermonkey let's settle on beta? That could be a bit late for very bleeding-edge extensions but I feel like that's reasonable, also.

Does this sound reasonable?

**Comment by wagnerand** [comment]
Sounds reasonable.

I had a look at ftp, but I can't find *jsshell* binaries for beta though.

**Comment by wagnerand** [comment]
Seems like we're stuck with Nightly then.

Mid-term, we should automate the release process so a new version is created a day before Nightly moves to Beta.
